---
- name: web
  hosts: _web
  become: true
    #  vars_files:
    #      - variable.yaml
            #vars:
    #          ansible_ssh_private_key_file: '{{ key_name }}'
  tasks:
          - name: enabledbphp
            shell: amazon-linux-extras enable lamp-mariadb10.2-php7.2
          - name: installdbphp
            shell: amazon-linux-extras install -y lamp-mariadb10.2-php7.2
          - name: dbhostinsert
            shell: sed -i "s/dbhost/RDSendpoint}/g" /var/www/html/insert.php