---
- name: web
  hosts: webservers
  become: true
    #  vars_files:
    #      - variable.yaml
            #vars:
    #          ansible_ssh_private_key_file: '{{ key_name }}'
  tasks:
          - name: apache
            yum:
                    name: httpd
                    state: latest
          - name: start
            service:
                    name: httpd
                    state: started
                    enabled: true
            ignore_errors: true
          - name: html
            copy:
                    src: ./html/*
                    dest: /var/www/html/
          - name: restart
            systemd:
                    name: httpd
                    state: restarted
                    enabled: true
